//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Editor.rc에서 사용되고 있습니다.
//
#define IDD_DELETEALL                   2
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_MAIN_MENU                   130
#define IDD_STATE                       316
#define IDD_SPRITE                      318
#define IDD_THEONE                      328
#define IDD_TRANS                       330
#define IDD_DLG_NONECOM                 332
#define IDD_ADDCOMPO                    334
#define IDD_DLG_SPRITERENDER            336
#define IDD_DLG_SPRITESELECT            339
#define IDD_PANZA                       341
#define IDD_BOTTOM                      342
#define IDD_BIRD                        347
#define IDD_LAUNCHER                    351
#define IDD_GRASS                       353
#define IDD_PIG                         355
#define IDC_MENUTAB                     1000
#define IDC_SCENELIST                   1005
#define IDC_CURSCENENAME                1007
#define IDC_SCENE_NAME                  1008
#define IDC_SCENECREATOR                1009
#define IDC_SPRITEV                     1009
#define IDC_TREE1                       1010
#define IDC_SPRITENAME                  1020
#define IDC_SPRITEU                     1021
#define IDC_LOAD                        1023
#define IDC_SAVE                        1024
#define IDC_ONECREATOR                  1025
#define IDC_BIRDCREATOR                 1025
#define IDC_ONETREE                     1026
#define IDC_XPOS                        1027
#define IDC_YPOS                        1028
#define IDC_BOTTOMCREATOR               1028
#define IDC_ZPOS                        1029
#define IDC_ADD_COMBTN                  1029
#define IDC_LAUNCHERCREATOR             1029
#define IDC_XROTATE                     1030
#define IDC_MIDDLEPAN                   1030
#define IDC_YROTATE                     1031
#define IDC_IMAGE_SLT                   1031
#define IDC_PIGCREATOR                  1031
#define IDC_ZROTATE                     1032
#define IDC_SPRITE_COLORBTN             1032
#define IDC_BOMBCREATOR                 1032
#define IDC_XSCALE                      1033
#define IDC_STATESAVEBTN                1033
#define IDC_GRASSCREATOR                1033
#define IDC_YSCALE                      1034
#define IDC_UVSLIDER                    1034
#define IDC_SMALLPAN                    1034
#define IDC_STATESAVEBTN2               1034
#define IDC_STATELOADBTN                1034
#define IDC_ZSCALE                      1035
#define IDC_UVINDEX                     1035
#define IDC_GIANTPAN                    1035
#define IDC_BIGPAN                      1036
#define IDC_XPOS2                       1036
#define IDC_YPOS2                       1037
#define IDC_ZPOS2                       1038
#define IDC_XROTATE2                    1039
#define IDC_YROTATE2                    1040
#define IDC_ZROTATE2                    1041
#define IDC_XSCALE2                     1042
#define IDC_YSCALE2                     1043
#define IDC_ZSCALE2                     1044
#define IDC_ADDCOMBO                    1046
#define IDC_ICERADIO                    1054
#define IDC_WOODRADIO                   1055
#define IDC_STONERADIO                  1056
#define IDC_ABSTRIRADIO                 1057
#define IDC_RIATRIRADIO                 1058
#define IDC_ABSRECTRADIO                1059
#define IDC_ANGRECT                     1060
#define IDC_CIRCLERADIO                 1061
#define IDC_SMALLRADIO                  1062
#define IDC_MIDDLERADIO                 1063
#define IDC_BIGRADIO                    1064
#define IDC_GIANTRADIO                  1065
#define IDC_MATERIALGR                  1066
#define IDC_SHAPEGR                     1067
#define IDC_SIZEGR                      1068
#define IDC_PANMASS                     1069
#define IDC_PANINER                     1070
#define IDC_PANCENTERX                  1071
#define IDC_PANCENTERY                  1072
#define IDC_GRAVTYX                     1072
#define IDC_GRAVITYX                    1072
#define IDC_PANDES                      1073
#define IDC_GRAVITYY                    1073
#define IDC_PANFIRC                     1074
#define IDC_PANSHAPECOMBO               1074
#define IDC_PANREDI                     1075
#define IDC_BUTTON1                     1076
#define IDC_PANZASAVE                   1076
#define IDC_BOTTOMEDIT                  1076
#define IDC_DELETEALL                   1076
#define IDC_PANZALOAD                   1077
#define IDC_PANZASAVE2                  1077
#define IDC_WHOGR                       1078
#define IDC_PANZALOAD2                  1078
#define IDC_BOMBRADIO                   1079
#define IDC_BLUERADIO                   1080
#define IDC_BUBBLERADIO                 1081
#define IDC_CHUCKRADIO                  1082
#define IDC_HALRADIO                    1083
#define IDC_MATILDARADIO                1084
#define IDC_MIGHTYRADIO                 1085
#define IDC_REDRADIO                    1086
#define IDC_TERENCERADIO                1087
#define IDC_BIRDSAVE                    1089
#define IDC_BIRDLOAD                    1090
#define IDC_BIRDMASS                    1091
#define IDD_CREATE                      1092
#define IDC_LBOTTOM                     1097

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        357
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
